# Fourier Transform
The French mathematician Jean Joseph Fourier developed Fourier
transforms in an attempt to solve the heat equation. During the process, he recognized that a periodic function can be expressed as infinite
sums of sines and cosines of different frequencies, now known as the
Fourier series.

* Fourier transform is an extension of the Fourier series to non-periodic functions. Fourier transform is a representation in which any function can be expressed as the integral of sines and cosines multiplied with the weighted function.
* Also, any function represented in either Fourier series or transform can be reconstructed completely by an inverse process => Inverse Fourier Transform.
=> After the development of the fast fourier transform algorithm, FFT, the applications of Fourier transform have affected several fields, remote sensing, signal processing and image processing. 

**In Image processing, Fourier Transform are used for:**
>    * Image Filtering
>    * Image Compression
>    * Image Enhancement 
>    * Image Restoration
>    * Image Analysis
>    * Image Reconstruction




In [1]:
import math, numpy
import scipy.fftpack as fftim


In [2]:
import scipy.misc 
from  PIL import Image
import matplotlib.pyplot as plt

In [3]:
# Open and check the image

a = Image.open('../ThesisWork/Images/12.gif')
a.show()

In [4]:
# a is converted into an ndarray
b = numpy.asarray(a)

# performing FFT

c = abs(fftim.fft2(b))

# shifting the Fourier frequence image

d= fftim.fftshift(c)


# Convertinng the d to floating type and saving it

d.astype('float').tofile('../Image Processing/fft1_ouput.raw')

*__The Fast Fourier transform is obtained using the fft2 function
and only the absolute value is obtained for visualization. The absolute
value image of FFT is then shifted, so that the center of the image is
the center of the Fourier spectrum. The center pixel corresponds to a
frequency of 0 in both directions. Finally, the shifted image is saved as
a raw file.__*


>__[rawpy](https://pypi.org/project/rawpy/)__ Important

> __[Tutorials](https://packaging.python.org/en/latest/tutorials/installing-packages/)__

In [5]:
# conda install rawpy
# !pip install rawpy

In [6]:
import rawpy
import imageio

In [7]:
# paths = 'C:/Users/jawad/OneDrive - University Of Central Asia/Study/UCA/8th Semester/FYP/ImageProcessing/Image Processing/fft1_output.raw'
raw = rawpy.imread('../Image Processing/fft1_output.raw')
rgb = raw.postprocess()
imageio.imsave('default.tiff', rgb)

LibRawIOError: b'Input/output error'

In [ ]:
# Find bad pixels using multiple RAW files and repair them:


import rawpy.enhance


bad_pixels = rawpy.enhance.find_bad_pixels(path)

for path in paths:
    with rawpy.imread(path) as raw:
        rawpy.enhance.repair_bad_pixels(raw, bad_pixels, method='median')
        rgb = raw.postprocess()
    imageio.imsave(path + '.tiff', rgb)

## Convolution

> **Convolution is a mathematical operation that expresses the integral
of the overlap between two functions. A simple example is a blurred
image, which is obtained by convolving an un-blurred image with a
blurring function**


There are many cases of blurred images that we see in real life. A
photograph of a car moving at high speed is blurred due to motion.
A photograph of a star obtained from a telescope is blurred by the
particles in the atmosphere. A wide-field microscope image of an object
is blurred by a signal from out-of-plane. Such blurring can be modeled
as convolution operation and eliminated by the inverse process called
deconvolution.

* __The operation is simpler in Fourier space than in real space but depending on the size of the  mage and the functions used, the former can be computationally efficient. In Fourier space, convolution is performed on the whole image at once. However, in spatial domain convolution is  erformed by sliding the filter window on the image.__

## Filtering in Frequency Domain

In lowpass filters, only low frequencies from the
Fourier transform are used while high frequencies are blocked. Similarly,
in highpass filters, only high frequencies from the Fourier transform are
used while the low frequencies are blocked. Lowpass filters are used to
smooth the image or reduce noise whereas highpass filters are used
to sharpen edges. In each case, three different filters, namely; ideal,
Butterworth and Gaussian, are considered. The three filters differ in
the creation of the windows used in filtering.
### Low-pass filter
* For a given image, after the convolution function is defined, the ideal lowpass filter can be performed with element by element multiplication of the FFT of the image and the convolution function. Then the inverse FFT is performed on the convolved function to get the output image. The Python code for the ideal lowpass filter is given below.


In [21]:
import scipy.misc
import numpy as np
import math
from  PIL import Image
import matplotlib.pyplot as plt

import scipy.fftpack as fftim

In [22]:
# Opening the image and converting it to grayscale
a=Image.open('../ThesisWork/Images/12.gif')
a.size
# a.show()

(512, 512)

In [23]:
# a is converted into an ndarray
b = np.asarray(a)
print(b)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [24]:
# Performing FFT
c=fftim.fft2(b)
# Shfting the Fourier frequency image
d=fftim.fftshift(c)

In [25]:
# Initializing variables for convolution function
M= d.shape[0]
N= d.shape[1]
# H is defined and values in H are initialized to 1
H = np.ones((M,N))

center1=M/2
center2=N/2

d_0=30.0 # Cut-off radius



In [26]:
# defining the convolution function for ILPF

for i in range(1,M):
    for j in range(1,N):
        r1=(i-center1)**2 + (j-center2)**2
        
        # euclidean distance from origin is computed
        r= math.sqrt(r1)
        
        # Using cut-off radius to eli,inate high frequency 
        if r>d_0:
            H[i,j]=0.0
            
# Converting H to an Image
H=Image.fromarray(H)

# Performing the convolution
con=d*H

#Computing the magnitude of the inverse FFT
e = abs(fftim.ifft2(con))
#e is converted from an ndarray to an image
lowpass_filter = Image.fromarray(e)

# Saving the image 
lowpass_filter.save('../Image Processing/ilowpass_ouput.gif')

In [27]:
lowpass_filter.show()

*The image is read and its Fourier transform is determined using the
fft2 function. The Fourier spectrum is shifted to the center of the image
using the fftshift function. A filter (H) is created by assigning a value of
1 to all pixels within a radius of d 0 and 0 otherwise. Finally, the filter
(H) is convolved with the image (d) to obtain the convolved Fourier
image (con). This image is inverted using ifft2 to obtain the filtered
image in spatial domain. Since high frequencies are blocked, the image
is blurred.*

> A simple image compression technique can be created using the
Fourier Transform 123
concept of lowpass filtering. In this technique, all high frequency data
is cleared and only the low frequency data is stored. This reduces the
number of Fourier coefficients stored and consequently needs less storage space on the disk. During the process of displaying the image, an
inverse Fourier transform can be obtained to convert the image to spatial domain. Such an image will suffer from blurring, as high frequency
information is not stored. A proper selection of the cut-off radius is
more important in image compression to avoid blurring and loss of
crucial data in the decompressed image.

### Butterworth Lowpass filter


In [28]:
import scipy.misc
import numpy as np
import math
from  PIL import Image
import matplotlib.pyplot as plt

import scipy.fftpack as fftim


# Opening the image and converting it to grayscale
a=Image.open('../ThesisWork/Images/12.gif')
a.size
# a.show()


# a is converted into an ndarray
b = np.asarray(a)
print(b)

# Performing FFT
c=fftim.fft2(b)
# Shfting the Fourier frequency image
d=fftim.fftshift(c)


# Initializing variables for convolution function
M= d.shape[0]
N= d.shape[1]
# H is defined and values in H are initialized to 1
H = np.ones((M,N))

center1=M/2
center2=N/2

d_0=30.0 # Cut-off radius

t1=1 # the order of BLPF
t2= 2*t1


# defining the convolution function for ILPF

for i in range(1,M):
    for j in range(1,N):
        r1=(i-center1)**2 + (j-center2)**2
        
        # euclidean distance from origin is computed
        r= math.sqrt(r1)
        
        # Using cut-off radius to eli,inate high frequency 
        if r>d_0:
            H[i,j]=1/(1+(r/d_0)**t1)
            
            
# Converting H to an Image
H=Image.fromarray(H)

# Performing the convolution
con=d*H

#Computing the magnitude of the inverse FFT
e = abs(fftim.ifft2(con))
#e is converted from an ndarray to an image
butterworth_losspass = Image.fromarray(e)

# Saving the image 
butterworth_losspass.save('../Image Processing/butterworth_losspass_ouput.gif')

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
butterworth_losspass.show()

### Gaussian Lowpass Filter


In [29]:
import scipy.misc
import numpy as np
import math
from  PIL import Image
import matplotlib.pyplot as plt

import scipy.fftpack as fftim


# Opening the image and converting it to grayscale
a=Image.open('../ThesisWork/Images/12.gif')
a.size
# a.show()


# a is converted into an ndarray
b = np.asarray(a)
print(b)

# Performing FFT
c=fftim.fft2(b)
# Shfting the Fourier frequency image
d=fftim.fftshift(c)


# Initializing variables for convolution function
M= d.shape[0]
N= d.shape[1]
# H is defined and values in H are initialized to 1
H = np.ones((M,N))

center1=M/2
center2=N/2

d_0=30.0 # Cut-off radius

t1=1 # the order of BLPF
t2= 2*t1


# defining the convolution function for ILPF

for i in range(1,M):
    for j in range(1,N):
        r1=(i-center1)**2 + (j-center2)**2
        
        # euclidean distance from origin is computed
        r= math.sqrt(r1)
        
        # Using cut-off radius to eli,inate high frequency 
        if r>d_0:
            H[i,j]=math.exp(-r**2/t1**2)
            
            
# Converting H to an Image
H=Image.fromarray(H)

# Performing the convolution
con=d*H

#Computing the magnitude of the inverse FFT
e = abs(fftim.ifft2(con))
#e is converted from an ndarray to an image
gassuian_lowpass = Image.fromarray(e)

# Saving the image 
gassuian_lowpass.save('../Image Processing/gassuian_lowpass_ouput.gif')

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
gassuian_lowpass.show()

## Ideal Highpass Filter


In [30]:
import scipy.misc
import numpy as np
import math
from  PIL import Image
import matplotlib.pyplot as plt

import scipy.fftpack as fftim


# Opening the image and converting it to grayscale
a=Image.open('../ThesisWork/Images/12.gif')
a.size
# a.show()


# a is converted into an ndarray
b = np.asarray(a)
print(b)

# Performing FFT
c=fftim.fft2(b)
# Shfting the Fourier frequency image
d=fftim.fftshift(c)


# Initializing variables for convolution function
M= d.shape[0]
N= d.shape[1]
# H is defined and values in H are initialized to 1
H = np.ones((M,N))

center1=M/2
center2=N/2

d_0=30.0 # Cut-off radius



# defining the convolution function for ILPF

for i in range(1,M):
    for j in range(1,N):
        r1=(i-center1)**2 + (j-center2)**2
        
        # euclidean distance from origin is computed
        r= math.sqrt(r1)
        
        # Using cut-off radius to eli,inate high frequency 
        if 0<r<d_0 :
            H[i,j]=0.0
            
            
# Converting H to an Image
H=Image.fromarray(H)

# Performing the convolution
con=d*H

#Computing the magnitude of the inverse FFT
e = abs(fftim.ifft2(con))
#e is converted from an ndarray to an image
ideal_highpass = Image.fromarray(e)

# Saving the image 
ideal_highpass.save('../Image Processing/ideal_highpass_ouput.gif')

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
ideal_highpass.show()

## Butterworth Highpass 

In [31]:
import scipy.misc
import numpy as np
import math
from  PIL import Image
import matplotlib.pyplot as plt

import scipy.fftpack as fftim


# Opening the image and converting it to grayscale
a=Image.open('../ThesisWork/Images/12.gif')
a.size
# a.show()


# a is converted into an ndarray
b = np.asarray(a)
print(b)

# Performing FFT
c=fftim.fft2(b)
# Shfting the Fourier frequency image
d=fftim.fftshift(c)


# Initializing variables for convolution function
M= d.shape[0]
N= d.shape[1]
# H is defined and values in H are initialized to 1
H = np.ones((M,N))

center1=M/2
center2=N/2

d_0=30.0 # Cut-off radius
t1=1 # the order of BHPF
t2=2*t1


# defining the convolution function for ILPF

for i in range(1,M):
    for j in range(1,N):
        r1=(i-center1)**2 + (j-center2)**2
        
        # euclidean distance from origin is computed
        r= math.sqrt(r1)
        
        # Using cut-off radius to eli,inate high frequency 
        if 0<r<d_0 :
            H[i,j]=1/(1+(r/d_0)**t2)
            
            
# Converting H to an Image
H=Image.fromarray(H)

# Performing the convolution
con=d*H

#Computing the magnitude of the inverse FFT
e = abs(fftim.ifft2(con))
#e is converted from an ndarray to an image
butterworth_highpass = Image.fromarray(e)

# Saving the image 
butterworth_highpass.save('../Image Processing/butterworth_highpass_ouput.gif')

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
butterworth_highpass.show()

## Gaussain highpass Filter


In [32]:
import scipy.misc
import numpy as np
import math
from  PIL import Image
import matplotlib.pyplot as plt

import scipy.fftpack as fftim


# Opening the image and converting it to grayscale
a=Image.open('../ThesisWork/Images/12.gif')
a.size
# a.show()


# a is converted into an ndarray
b = np.asarray(a)
print(b)

# Performing FFT
c=fftim.fft2(b)
# Shfting the Fourier frequency image
d=fftim.fftshift(c)


# Initializing variables for convolution function
M= d.shape[0]
N= d.shape[1]
# H is defined and values in H are initialized to 1
H = np.ones((M,N))

center1=M/2
center2=N/2

d_0=30.0 # Cut-off radius

t1=1 # the order of BLPF
t2= 2*t1


# defining the convolution function for ILPF

for i in range(1,M):
    for j in range(1,N):
        r1=(i-center1)**2 + (j-center2)**2
        
        # euclidean distance from origin is computed
        r= math.sqrt(r1)
        
        # Using cut-off radius to eli,inate high frequency 
        if 0<r<d_0:
            H[i,j]=math.exp(-r**2/t1**2)
            
            
# Converting H to an Image
H=Image.fromarray(H)

# Performing the convolution
con=d*H

#Computing the magnitude of the inverse FFT
e = abs(fftim.ifft2(con))
#e is converted from an ndarray to an image
gassuian_highpass = Image.fromarray(e)

# Saving the image 
gassuian_highpass.save('../Image Processing/gassuian_highpass_ouput.gif')

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:

gassuian_highpass.show()

## Bandpass filter


In [33]:
import scipy.misc
import numpy as np
import math
from  PIL import Image
import matplotlib.pyplot as plt

import scipy.fftpack as fftim


# Opening the image and converting it to grayscale
a=Image.open('../ThesisWork/Images/12.gif')
a.size
# a.show()


# a is converted into an ndarray
b = np.asarray(a)
print(b)

# Performing FFT
c=fftim.fft2(b)
# Shfting the Fourier frequency image
d=fftim.fftshift(c)


# Initializing variables for convolution function
M= d.shape[0]
N= d.shape[1]
# H is defined and values in H are initialized to 1
H = np.ones((M,N))

center1=M/2
center2=N/2

d_0=30.0 # Minimum Cut-off radius
d_1=50.0 # Maximum Cut-off radius


# defining the convolution function for ILPF

for i in range(1,M):
    for j in range(1,N):
        r1=(i-center1)**2 + (j-center2)**2
        
        # euclidean distance from origin is computed
        r= math.sqrt(r1)
        
        # Using cut-off radius to eli,inate high frequency 
        if r>d_0 and r<d_1:
            H[i,j]=1.0
            
            
# Converting H to an Image
H=Image.fromarray(H)

# Performing the convolution
con=d*H

#Computing the magnitude of the inverse FFT
e = abs(fftim.ifft2(con))
#e is converted from an ndarray to an image
band_pass = Image.fromarray(e)

# Saving the image 
band_pass.save('../Image Processing/band_pass_ouput.gif')

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
band_pass.show()

# Summary
* Lowpass filters are used for noise reduction or smoothing. Highpass filters are used for edge enhancement or sharpening.


* In lowpass and highpass filters ideal, Butterworth and Gaussian were considered.


* A bandpass filter has minimum cut-off and maximum cut-off radii.


* Convolution can be viewed as the process of combining two images. Convolution is multiplication in Fourier domain. The inverse process is called deconvolution.


* Fourier transform can be used for image filtering, compression, enhancement, restoration and analysis.


# End of Chpt 6